services:
  db:
    image: postgres:15-alpine
    container_name: camagru-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: camagru-backend
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  proxy:
    image: caddy:2-alpine
    container_name: camagru-proxy
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/var/www/frontend
    depends_on:
      - backend

volumes:
  pgdata: