// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, user_id, purpose, expired_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateEmailTokenParams struct {
	TokenHash string
	UserID    uuid.UUID
	Purpose   string
	ExpiredAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.ExecContext(ctx, createEmailToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiredAt,
	)
	return err
}

const deleteEmailTokensByUserAndPurpose = `-- name: DeleteEmailTokensByUserAndPurpose :exec
DELETE FROM email_tokens
WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailTokensByUserAndPurposeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) DeleteEmailTokensByUserAndPurpose(ctx context.Context, arg DeleteEmailTokensByUserAndPurposeParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailTokensByUserAndPurpose, arg.UserID, arg.Purpose)
	return err
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT token_hash, user_id, purpose, expired_at, used_at, created_at FROM email_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetEmailToken(ctx context.Context, tokenHash string) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailToken, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Purpose,
		&i.ExpiredAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens
SET used_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, markEmailTokenUsed, tokenHash)
	return err
}
