// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (post_id, user_id)
VALUES (
    $1,
    $2
)
`

type CreateLikeParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.ExecContext(ctx, createLike, arg.PostID, arg.UserID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE post_id = $1 AND user_id = $2
`

type DeleteLikeParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLike, arg.PostID, arg.UserID)
	return err
}

const getLike = `-- name: GetLike :one
SELECT post_id, user_id, created_at FROM likes
WHERE post_id = $1 AND user_id = $2 LIMIT 1
`

type GetLikeParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, getLike, arg.PostID, arg.UserID)
	var i Like
	err := row.Scan(&i.PostID, &i.UserID, &i.CreatedAt)
	return i, err
}
