// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiredAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
