// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthIdentityParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, createOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentityByProvider = `-- name: GetOAuthIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2 LIMIT 1
`

type GetOAuthIdentityByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthIdentityByProvider(ctx context.Context, arg GetOAuthIdentityByProviderParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOAuthIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentityByUser = `-- name: GetOAuthIdentityByUser :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_identities
WHERE user_id = $1 AND provider = $2 LIMIT 1
`

type GetOAuthIdentityByUserParams struct {
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) GetOAuthIdentityByUser(ctx context.Context, arg GetOAuthIdentityByUserParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOAuthIdentityByUser, arg.UserID, arg.Provider)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}
