// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, image_path, overlay_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, image_path, overlay_id, created_at
`

type CreatePostParams struct {
	UserID    uuid.UUID
	ImagePath string
	OverlayID sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.UserID, arg.ImagePath, arg.OverlayID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImagePath,
		&i.OverlayID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, image_path, overlay_id, created_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImagePath,
		&i.OverlayID,
		&i.CreatedAt,
	)
	return i, err
}

const getPostOwnerNotifyInfo = `-- name: GetPostOwnerNotifyInfo :one
SELECT users.id AS user_id, users.email, users.notify_on_comment
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.id = $1
`

type GetPostOwnerNotifyInfoRow struct {
	UserID          uuid.UUID
	Email           string
	NotifyOnComment bool
}

func (q *Queries) GetPostOwnerNotifyInfo(ctx context.Context, id uuid.UUID) (GetPostOwnerNotifyInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getPostOwnerNotifyInfo, id)
	var i GetPostOwnerNotifyInfoRow
	err := row.Scan(&i.UserID, &i.Email, &i.NotifyOnComment)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT
    posts.id,
    posts.user_id,
    users.username,
    posts.image_path,
    posts.overlay_id,
    posts.created_at,
    COUNT(DISTINCT likes.user_id) AS like_count,
    COUNT(DISTINCT comments.id) AS comment_count,
    COALESCE(BOOL_OR(likes.user_id = $3::uuid), false)::bool AS liked_by_me
FROM posts
JOIN users ON users.id = posts.user_id
LEFT JOIN likes ON likes.post_id = posts.id
LEFT JOIN comments ON comments.post_id = posts.id
GROUP BY posts.id, users.username
ORDER BY posts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit    int32
	Offset   int32
	ViewerID uuid.NullUUID
}

type ListPostsRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Username     string
	ImagePath    string
	OverlayID    sql.NullString
	CreatedAt    time.Time
	LikeCount    int64
	CommentCount int64
	LikedByMe    bool
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.ImagePath,
			&i.OverlayID,
			&i.CreatedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT id, user_id, image_path, overlay_id, created_at FROM posts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPostsByUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImagePath,
			&i.OverlayID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
